package org.genivi.commonapi.someip.generator;

/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'SomeIPServiceAddress'
*******************************************************************************/
import org.franca.core.franca.FInterface;
import org.franca.deploymodel.core.FDeployedInterface;

/**
 * Accessor for deployment properties for 'SomeIPServiceAddress' specification
 */		
public class SomeIPServiceAddressInterfacePropertyAccessor
{
	
	private FDeployedInterface target;

	public SomeIPServiceAddressInterfacePropertyAccessor (FDeployedInterface target) {
		this.target = target;
	}
	
	public Integer getServiceID (FInterface obj) {
		return target.getInteger(obj, "ServiceID");
	}
	
	
}
