package org.genivi.commonapi.someip.generator;

/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'SomeIPServiceAddress'
*******************************************************************************/
import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'SomeIPServiceAddress' specification
 */		
public class SomeIPServiceAddressProviderPropertyAccessor
{
	
	private FDeployedProvider target;

	public SomeIPServiceAddressProviderPropertyAccessor (FDeployedProvider target) {
		this.target = target;
	}
	
	
}
