/*******************************************************************************
* This file has been generated by Franca's FDeployGenerator.
* Source: deployment spec 'someip.ServiceSpecification'
*******************************************************************************/
package someip;

import org.franca.deploymodel.core.FDeployedProvider;

/**
 * Accessor for deployment properties for 'someip.ServiceSpecification' specification
 */		
public class ServiceSpecificationProviderPropertyAccessor
{
	
	private FDeployedProvider target;

	public ServiceSpecificationProviderPropertyAccessor (FDeployedProvider target) {
		this.target = target;
	}
	
	
}
